name: "🙋‍♂️ Assign me"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  set_assignee:
    uses: renebentes/.github/.github/workflows/assign-me.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
